
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import type { Database as AppDatabase } from '@/types/auth';

const SUPABASE_URL = "https://fmenixxpujncrhntslyj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtZW5peHhwdWpuY3JobnRzbHlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MzQ0NDUsImV4cCI6MjA2MjMxMDQ0NX0.hjYGSuskjZ3ZeZJfBJh2m37g0R3AT8cyVEBWG2nX1qo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Merge generated Database with our app's database types
type MergedDatabase = Database & AppDatabase;

export const supabase = createClient<MergedDatabase>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
